// Blog/article content. Each post is plain data, add, edit or remove freely.
// `body` is an array of blocks: {h: 'heading'} or {p: 'paragraph'} or {list: [..]}.
// Good for SEO: useful, original, keyword-relevant articles around your industry.

export const posts = [
  {
    slug: 'how-to-choose-a-garment-manufacturer-in-bangladesh',
    title: 'How to choose a garment manufacturer in Bangladesh',
    excerpt: 'A practical checklist for sourcing teams, what to verify before you place your first bulk order with a clothing factory.',
    category: 'Sourcing',
    date: '2026-05-28',
    readTime: '6 min',
    keywords: 'garment manufacturer Bangladesh, clothing factory sourcing, apparel supplier checklist, RMG sourcing',
    body: [
      { p: "Bangladesh is the world's second-largest apparel exporter, which means buyers have thousands of factories to choose from, and very uneven quality between them. The right partner protects your margins and your reputation; the wrong one quietly costs you both. Here is the checklist our own buyers use." },
      { h: 'Confirm the factory actually makes your product' },
      { p: 'Many suppliers list every category on their website but specialise in only one. Ask for recent production photos of your specific product type, the machine count for that line, and references from buyers ordering something similar to you.' },
      { h: 'Verify compliance independently' },
      { p: 'A self-declared "compliant" factory means little. Ask for current third-party audit reports, WRAP, amfori BSCI, Sedex SMETA, and check the dates. A factory that sends documentation without being chased is signalling how the whole relationship will run.' },
      { h: 'Pressure-test lead times before you commit' },
      { list: ['Ask for a realistic timeline in writing, fabric-in to ship.', 'Ask what their on-time shipment rate was last year.', 'Ask what happens, specifically, if a shipment slips.'] },
      { p: 'Vague answers here are the single biggest predictor of problems later.' },
      { h: 'Start small, then scale' },
      { p: 'A trial order tells you more than any factory visit. Watch how they handle sampling, communication and a real QC inspection before you move your main volume across.' },
    ],
  },
  {
    slug: 'understanding-moq-gsm-and-lead-times',
    title: 'MOQ, GSM and lead times: the terms that decide your order',
    excerpt: 'A plain-language guide to the three numbers that quietly shape cost, quality and delivery on every apparel order.',
    category: 'Guides',
    date: '2026-05-12',
    readTime: '5 min',
    keywords: 'MOQ meaning apparel, GSM fabric weight, garment lead time, apparel manufacturing terms',
    body: [
      { p: 'Three numbers come up in every manufacturing conversation. Understanding them up front saves a lot of back-and-forth, and a lot of money.' },
      { h: 'MOQ, minimum order quantity' },
      { p: "The smallest run a factory will accept, usually per style and per colour. Lower MOQs give you flexibility; higher MOQs usually mean a lower per-unit price. If a quoted MOQ feels high, ask whether it's driven by fabric minimums (often the real reason) and whether colours can be combined." },
      { h: 'GSM, grams per square metre' },
      { p: 'Fabric weight. A light summer tee might be 140 GSM; a heavyweight hoodie 320 GSM or more. GSM affects feel, durability, drape and cost, so specifying it precisely keeps your bulk consistent with your sample.' },
      { h: 'Lead time' },
      { p: 'The clock from approved order to shipment. It includes fabric and trim sourcing, cutting, sewing, washing, finishing and QC, not just stitching. Always ask whether a quoted lead time starts at order confirmation or at fabric-in, because the difference can be weeks.' },
    ],
  },
  {
    slug: 'compliance-certifications-explained',
    title: 'Compliance certifications explained: WRAP, BSCI, OEKO-TEX and more',
    excerpt: 'What the major apparel certifications actually mean, and which ones your buyers are likely to ask you for.',
    category: 'Compliance',
    date: '2026-04-20',
    readTime: '7 min',
    keywords: 'WRAP certification, amfori BSCI, OEKO-TEX Standard 100, Sedex SMETA, GOTS GRS apparel compliance',
    body: [
      { p: 'Certifications are how a factory proves, to an outside standard, that it is run responsibly. Here is a quick map of the ones that come up most in apparel sourcing.' },
      { h: 'Social & ethical' },
      { list: ['WRAP, Worldwide Responsible Accredited Production: factory-level social compliance, graded Platinum/Gold/Silver.', 'amfori BSCI, a widely used social audit framework covering labour rights and working conditions.', 'Sedex SMETA, a four-pillar ethical audit (labour, health & safety, environment, business ethics).'] },
      { h: 'Product & environmental' },
      { list: ['OEKO-TEX Standard 100 · tests finished textiles for harmful substances.', 'GOTS, Global Organic Textile Standard, for certified organic fibre.', 'GRS, Global Recycled Standard, for verified recycled content.'] },
      { h: 'The honest point' },
      { p: 'A certificate is only as good as it is current and verifiable. The factories worth working with treat each audit as a standard to exceed, not a hurdle to clear once, and they hand over the paperwork without being asked.' },
    ],
  },
  {
    slug: 'sustainable-apparel-sourcing-trends',
    title: 'Sustainable apparel sourcing: what brands are asking for now',
    excerpt: 'Recycled content, water data and traceability are moving from nice-to-have to procurement requirement. Here is what that means on the factory floor.',
    category: 'Sustainability',
    date: '2026-03-30',
    readTime: '6 min',
    keywords: 'sustainable apparel sourcing, recycled polyester GRS, water recycling textile, supply chain traceability',
    body: [
      { p: 'Sustainability requirements used to live in a brand\u2019s marketing team. Increasingly they live in procurement, written into supplier scorecards. A few shifts worth planning for:' },
      { h: 'Verified materials, not vague claims' },
      { p: 'Buyers now want certified recycled or organic content (GRS, GOTS) rather than unbacked "eco" language. Factories that can document fibre origin win these programmes.' },
      { h: 'Measured resource use' },
      { p: 'Water and energy per garment are increasingly reported, not estimated. In-house effluent treatment, water recycling and on-site solar are becoming differentiators on the factory side.' },
      { h: 'Traceability' },
      { p: 'The ability to show where fabric and trims came from is becoming a condition of doing business with larger brands. The earlier a factory builds that record-keeping habit, the easier these conversations get.' },
    ],
  },
  {
    slug: 'corporate-gifting-that-gets-kept',
    title: "Corporate gifting that doesn't end up in a drawer",
    excerpt: 'How to pick branded merchandise people actually use, and why product quality decides whether your brand gets seen.',
    category: 'Corporate Gifts',
    date: '2026-03-08',
    readTime: '5 min',
    keywords: 'corporate gifting ideas, branded merchandise, promotional products, client gift sets',
    body: [
      { p: 'The point of a branded gift is repeat exposure: every time someone uses it, your logo is back in front of them. A gift that gets binned is wasted spend, no matter how cheap it was.' },
      { h: 'Pick for daily use' },
      { p: 'Drinkware, quality notebooks, weighted pens and good apparel get used for years. Novelty items get used once. Spend where the daily-use value is.' },
      { h: 'Quality is the message' },
      { p: 'Recipients read the quality of a gift as a signal about the brand behind it. A flimsy bottle says something you don\u2019t want it to say. This is exactly why branded apparel made in a real garment factory beats apparel bought in and hoped for.' },
      { h: 'Make the unboxing feel considered' },
      { p: 'Curated sets, proper packaging and a personal touch turn a giveaway into a gesture. That feeling is what people remember, and associate with you.' },
    ],
  },
]

export const getPost = (slug) => posts.find((p) => p.slug === slug)
